language: python
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.6"
install:
  - pip install pipenv
  - pipenv install
before_script:
  - psql -c 'create database visitrail_test;' -U postgres
  - python manage.py migrate
script:
  - coverage run --source='api' manage.py test && coverage report
after_success:
  - coveralls

